server:
  port: 8080

spring:
  application:
    name: organice-semana
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:Post123321}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: semana
  jpa:
    properties:
      hibernate:
        default_schema: semana
  mvc:
    format:
      date-time: "yyyy-MM-dd HH:mm:ss"

springdoc:
  api-docs:
    path: /dia/v3/api-docs
  swagger-ui:
    path: /dia/swagger-ui.html


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      base-path: /semana/actuator
      exposure:
        include: [ 'prometheus' ]