apiVersion: v1
kind: Service
metadata:
  name: semana
  labels:
    name: semana
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: semana